name: Flake8 Style Guide Enforcement

# https://github.com/mschwager/cohesion#flake8-support
# https://github.com/wemake-services/flake8-eradicate
# https://github.com/adamchainz/flake8-comprehensions
# https://github.com/terrencepreilly/darglint
# https://github.com/tylerwince/flake8-bandit
# https://github.com/PyCQA/flake8-bugbear
# https://github.com/dlint-py/dlint
# https://github.com/datatheorem/flake8-alfred
# https://github.com/gforcada/flake8-builtins
# https://github.com/Melevir/flake8-functions-names
# https://github.com/JBKahn/flake8-print
# https://github.com/m-burst/flake8-pytest-style
# https://github.com/afonasev/flake8-return
# https://github.com/Arkq/flake8-requirements
# https://github.com/MartinThoma/flake8-simplify
# https://github.com/best-doctor/flake8-variables-names
# https://github.com/PyCQA/pep8-naming
# https://github.com/Melevir/flake8-cognitive-complexity
# https://github.com/best-doctor/flake8-functions
# https://github.com/best-doctor/flake8-expression-complexity



on: [pull_request]

jobs:
  style_enforcer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 flake8-eradicate flake8-comprehensions darglint flake8-bandit flake8-bugbear
        python -m pip install dlint flake8-alfred flake8-builtins flake8-functions-names flake8-print flake8-pytest-style
        python -m pip install flake8-return flake8-requirements flake8-simplify flake8-variables-names pep8-naming
        python -m pip install flake8-cognitive-complexity flake8-functions flake8-expression-complexity
    - name: Run flake8
      uses: rbialon/flake8-annotations@v1
      with:
        checkName: 'style_enforcer'
      - name: Lint with flake8
            run: |
              pip install flake8
              # stop the build if there are Python syntax errors or undefined names
              flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
              # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
              flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics