name: Format with Black

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format
        uses: psf/black@stable
        with:
          options: "./"
      - uses: EndBug/add-and-commit@v7 
  

          
