name: Format with black and isort

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  format_code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: format with black
        uses: psf/black@stable
        with:
          options: "./"
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: order imports
        uses: isort/isort-action@master
        with:
          configuration: ""
      - name: add commit changes
        uses: EndBug/add-and-commit@v7
