name: Format with Black

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - uses: psf/black@stable
        with:
          options: "./"
      - uses: EndBug/add-and-commit@latest
