name: Format with Black

on: [push]

jobs:
  format_with_black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "./"
      - uses: EndBug/add-and-commit@v7
