name: Format with Black

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format
        uses: psf/black@stable
        with:
          options: "./"
      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          git commit -am "Format Python code with Black"
          git push
          
