name: Markdown Linter

on:
  pull_request:
      types: [opened, synchronize, reopened]
  push:
    branches:
      - '*'
      - '!main'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Run mdl
      uses: actionshub/markdownlint@main