on:
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: Sonar
jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest -v  --cov --cov-report=xml --cov-report=html
    - name: list files
      run: |
        ls
    - name: fix code coverage paths
      run: |
        sed -i 's/\/home\/runner\/work\/edr_query_parser\/edr_query_parser\//\/github\/workspace\//g' coverage.xml
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}